- id: '1674384218356'
  alias: Motion Sensor test
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.hue_motion_sensor_3_flur_motion
      light_target:
        area_id:
          - flur
          - bad
          - kuche
- id: '1674387650518'
  alias: Wohnzimmerlicht an (Schalter)
  description: ''
  trigger:
    - platform: device
      device_id: 7079a11ea5591a7dedce42d708f00e22
      domain: bosch_shc
      type: PRESS_SHORT
      subtype: UPPER_BUTTON
  condition: []
  action:
    - type: turn_on
      entity_id: light.hue_lightstrip_plus_1
      domain: light
    - type: turn_on
      entity_id: light.wohnzimmer_gross
      domain: light
    - type: turn_on
      entity_id: light.wohnzimmer_klein
      domain: light
  mode: single
