# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

# waste_collection_schedule:
#   sources:
#     - name: abfall_io
#       args:
#         key: !secret waste_collection_key
#         f_id_kommune: !secret waste_collection_kommune
#         f_id_bezirk: !secret waste_collection_bezirk
#         f_id_strasse: !secret waste_collection_strasse
#         f_id_strasse_hnr: !secret waste_collection_hnr
#         f_abfallarten:
#           - 66 # Gelber Sack
#           - 177 # Graue Tonne
#           - 951 # Grüne Tonne
#           - 190 # Strauchgutabfuhr
#           - 33 # Sperrmüll
#           - 347 # Problemabfallsammeltermine

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
# sensor: !include sensor.yaml
