# GitHub Integration
- platform: github
  access_token: !secret github_token
  repositories:
    - path: "cremetv/homeassistant"
      name: creme's Homeassistant Config

- platform: waste_collection_schedule
  name: abfall
